### ISSUE TITLE
Looking for someone to take over

### ISSUE THREAD

**Issue by grndctrl** [grndctrl/zed-gdscript#13]
Godot is just a hobby of mine, I am a webdev by trade. I like Zed, which is why I threw this together, but I don't know Rust to keep improving it.
Since I became a father, time for hobbies is scarce. And I rather want to put it in the game, then use it to keep working on this extension.

**Comment by NathanLovato** [comment]
Hey there! I'd be interested in maintaining this project. While I lack the time and Rust experience to implement features in the short term, I've been an open source project maintainer for a long time, including of the official Godot documentation

I initially wrote the package to support Godot in Emacs (that I've since handed over to the Godot project: https://github.com/godotengine/emacs-gdscript-mode/ ).

I would gladly review and merge contributions to this extension, and, if it's OK with you, I'd suggest eventually transferring it to the Godot Foundation, once it's a bit more fleshed out.

**Comment by grndctrl** [comment]
Hey Nathan, having this ultimately under the Godot Foundation sounds incredible. I greatly appreciate you reaching out. Are you on the Godot Engine discord or Godot Cafe? Might be easier to discuss there, you can add me: `mrkbrnd`

**Comment by NathanLovato** [comment]
Sure, I just sent you a private message on Discord!
